//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.MiServicio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MiServicio.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sandwichType del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateOrder", ReplyAction="*")]
        Cliente.MiServicio.CreateOrderResponse CreateOrder(Cliente.MiServicio.CreateOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente.MiServicio.CreateOrderResponse> CreateOrderAsync(Cliente.MiServicio.CreateOrderRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetOrderDetailsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderDetails", ReplyAction="*")]
        Cliente.MiServicio.GetOrderDetailsResponse GetOrderDetails(Cliente.MiServicio.GetOrderDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOrderDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<Cliente.MiServicio.GetOrderDetailsResponse> GetOrderDetailsAsync(Cliente.MiServicio.GetOrderDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateOrder", Namespace="http://tempuri.org/", Order=0)]
        public Cliente.MiServicio.CreateOrderRequestBody Body;
        
        public CreateOrderRequest() {
        }
        
        public CreateOrderRequest(Cliente.MiServicio.CreateOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sandwichType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int quantity;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string address;
        
        public CreateOrderRequestBody() {
        }
        
        public CreateOrderRequestBody(string sandwichType, int quantity, string address) {
            this.sandwichType = sandwichType;
            this.quantity = quantity;
            this.address = address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente.MiServicio.CreateOrderResponseBody Body;
        
        public CreateOrderResponse() {
        }
        
        public CreateOrderResponse(Cliente.MiServicio.CreateOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateOrderResult;
        
        public CreateOrderResponseBody() {
        }
        
        public CreateOrderResponseBody(string CreateOrderResult) {
            this.CreateOrderResult = CreateOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderDetails", Namespace="http://tempuri.org/", Order=0)]
        public Cliente.MiServicio.GetOrderDetailsRequestBody Body;
        
        public GetOrderDetailsRequest() {
        }
        
        public GetOrderDetailsRequest(Cliente.MiServicio.GetOrderDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int orderId;
        
        public GetOrderDetailsRequestBody() {
        }
        
        public GetOrderDetailsRequestBody(int orderId) {
            this.orderId = orderId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOrderDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOrderDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Cliente.MiServicio.GetOrderDetailsResponseBody Body;
        
        public GetOrderDetailsResponse() {
        }
        
        public GetOrderDetailsResponse(Cliente.MiServicio.GetOrderDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOrderDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetOrderDetailsResult;
        
        public GetOrderDetailsResponseBody() {
        }
        
        public GetOrderDetailsResponseBody(string GetOrderDetailsResult) {
            this.GetOrderDetailsResult = GetOrderDetailsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : Cliente.MiServicio.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<Cliente.MiServicio.WebService1Soap>, Cliente.MiServicio.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.MiServicio.CreateOrderResponse Cliente.MiServicio.WebService1Soap.CreateOrder(Cliente.MiServicio.CreateOrderRequest request) {
            return base.Channel.CreateOrder(request);
        }
        
        public string CreateOrder(string sandwichType, int quantity, string address) {
            Cliente.MiServicio.CreateOrderRequest inValue = new Cliente.MiServicio.CreateOrderRequest();
            inValue.Body = new Cliente.MiServicio.CreateOrderRequestBody();
            inValue.Body.sandwichType = sandwichType;
            inValue.Body.quantity = quantity;
            inValue.Body.address = address;
            Cliente.MiServicio.CreateOrderResponse retVal = ((Cliente.MiServicio.WebService1Soap)(this)).CreateOrder(inValue);
            return retVal.Body.CreateOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.MiServicio.CreateOrderResponse> Cliente.MiServicio.WebService1Soap.CreateOrderAsync(Cliente.MiServicio.CreateOrderRequest request) {
            return base.Channel.CreateOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.MiServicio.CreateOrderResponse> CreateOrderAsync(string sandwichType, int quantity, string address) {
            Cliente.MiServicio.CreateOrderRequest inValue = new Cliente.MiServicio.CreateOrderRequest();
            inValue.Body = new Cliente.MiServicio.CreateOrderRequestBody();
            inValue.Body.sandwichType = sandwichType;
            inValue.Body.quantity = quantity;
            inValue.Body.address = address;
            return ((Cliente.MiServicio.WebService1Soap)(this)).CreateOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Cliente.MiServicio.GetOrderDetailsResponse Cliente.MiServicio.WebService1Soap.GetOrderDetails(Cliente.MiServicio.GetOrderDetailsRequest request) {
            return base.Channel.GetOrderDetails(request);
        }
        
        public string GetOrderDetails(int orderId) {
            Cliente.MiServicio.GetOrderDetailsRequest inValue = new Cliente.MiServicio.GetOrderDetailsRequest();
            inValue.Body = new Cliente.MiServicio.GetOrderDetailsRequestBody();
            inValue.Body.orderId = orderId;
            Cliente.MiServicio.GetOrderDetailsResponse retVal = ((Cliente.MiServicio.WebService1Soap)(this)).GetOrderDetails(inValue);
            return retVal.Body.GetOrderDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Cliente.MiServicio.GetOrderDetailsResponse> Cliente.MiServicio.WebService1Soap.GetOrderDetailsAsync(Cliente.MiServicio.GetOrderDetailsRequest request) {
            return base.Channel.GetOrderDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Cliente.MiServicio.GetOrderDetailsResponse> GetOrderDetailsAsync(int orderId) {
            Cliente.MiServicio.GetOrderDetailsRequest inValue = new Cliente.MiServicio.GetOrderDetailsRequest();
            inValue.Body = new Cliente.MiServicio.GetOrderDetailsRequestBody();
            inValue.Body.orderId = orderId;
            return ((Cliente.MiServicio.WebService1Soap)(this)).GetOrderDetailsAsync(inValue);
        }
    }
}
